### PR TITLE
Add functions ROWS() and COLUMNS()

### PR DESCRIPTION
**Pull request by danielsjf**

### CODE REVIEW

**Comment by danielsjf** [comment]
Failing due to again the same tox issue, so #186 need to be merged first.

**Comment by danielsjf** [comment]
@brianmay, this one is ready to merge once #186 goes in for the tox fix (test will have to be reran)

**Comment by brianmay** [comment]
#186 has been merged now, so this can get fixed.

**Comment by danielsjf** [comment]
@brianmay, this one should be fine now.

**Pull request merged**
