### PR TITLE
Add sumifs

### PR DESCRIPTION
**Pull request by danielsjf**
This pull request adds the sumifs function.

### CODE REVIEW

**Comment by danielsjf** [comment]
Tests will only pass when #176 is merged.

**Comment by brianmay** [comment]
#176 is merged into Master now.

**Review by brianmay — APPROVED** [review]
Looks good to me. Will merge once tests pass.

**Comment by brianmay** [comment]
Also if there are any open issues that have been addressed by these pull requests, feel free to leave a comment saying so and/or closing it (if you can). Thanks.

**Comment by danielsjf** [comment]
@brianmay, checks pass

**Pull request merged**
