### PR TITLE
Tests that build a Spreadsheet from scratch with evaluations

### PR DESCRIPTION
**Pull request by danielsjf**
Instead of building the spreadsheet from a file, build it from scratch using commands. This allows us to set up more useful other tests without each time creating an excel file.

Builds upon #189.

### CODE REVIEW

**Comment by brianmay** [comment]
Something broken with numpy for Python versions over then 3.5????

**Comment by danielsjf** [comment]
@brianmay, how do you mean?

**Comment by brianmay** [comment]
I meant to followup on that comment, but I somehow managed to loose it. Not a problem anymore, travis tests passing.

**Comment by brianmay** [comment]
This one still needs updating.

**Comment by danielsjf** [comment]
@brianmay, this one can be merged.

**Pull request merged**
