### PR TITLE
Merging fix of Spreadsheet/ExcelCompiler, updated tests, Attempt 3

### PR DESCRIPTION
**Pull request by bradbase**
- Moved ExcelCompiler functionality to spreadsheet, keeping backwards compatibility for ExcelCompiler
- Added a second constructor to Spreadsheet to support the ability to create a Spreadsheet object with the newly acquired functionality
- Added a third constrictor called build_spreadsheet which is essentially a helper, running gen_graph() on your behalf
- re-named self.Range to self.range
- supported the Spreadsheet object move to cell_XXX method names
- some bug fixes based on testing utils.py
- updated requirements.txt
- updated setup.py
- fixed test_basic_evaluation to use the new cell_XXX methods for Spreadsheet object.
- fixed test_pruning to use the new cell_XXX methods for Spreadsheet object.
- fixed test_excel to use the new cell_XXX methods for Spreadsheet object.
- fixed test_spreadsheet to use the new cell_XXX methods for Spreadsheet object.
- added many tests, and fixed test_utils.

### CODE REVIEW

**Comment by bradbase** [comment]
I have run all the tests on my machine, all pass.  Have also run both examples, both run. And the Travis tests (above Python 2.7 run)

**Comment by Brad-eki** [comment]
We seem to have lost something with this commit.

My use case relies upon the ability to parse a subset of a spreadsheet.

`python

excel_compiler = ExcelCompiler(file_name, ignore_sheets=ignore_sheets)
excel_compiler.clean_pointer()
`


    parser = ExcelParser()
    tokens = parser.parse(model.formula)
    print(parser.prettyprint())
    inputs = parser.getOperandRanges()
    # koala_models[str(model.name.name)] = excel_compiler.gen_graph(inputs= inputs, outputs= [model.name.name])
    koala_models[str(model.name.name)] = excel_compiler.gen_graph()

    print("Successfully loaded model %s" % model.name)
    return 'Cached Model %s' % model.name


@xw.sub
def reload_koala(file_name, ignore_sheets= None, bootstrap_equations= None):
    """Loads the Excel workbook into a koala Spreadsheet object"""
    global excel_compiler
    print("Loading workbook")
    excel_compiler = ExcelCompiler(file_name, ignore_sheets=ignore_sheets)
    excel_compiler.clean_pointer()
    print("Workbook '%s' has been loaded." % file_name)
    print("Ignored worksheets %s" % ignore_sheets)

**Comment by bradbase** [comment]
needs a bugfix.

**Comment by bradbase** [comment]
The bug I thought was there isn't.

**Comment by bradbase** [comment]
There is certainly a bug.

It's not likely to affect the majority of users but is having an impact on my use case. So I'd say this PR is still ok.

I'm having trouble characterizing the bug though.

The bug is related to gen_graph no longer behaving correctly. Calling gen_graph looses state when you call it with arguments.

So this is fine:
from koala.ExcelCompiler import ExcelCompiler
from koala.tokenizer import ExcelParser
excel_compiler = ExcelCompiler(file_name, ignore_sheets=ignore_sheets)
excel_compiler.clean_pointer()
excel_compiler.gen_graph()

This is also fine:
from koala.ExcelCompiler import ExcelCompiler
from koala.tokenizer import ExcelParser
from koala.Spreadsheet import Spreadsheet
excel_compiler = Spreadsheet.from_file_name(file_name, ignore_sheets=ignore_sheets)
excel_compiler.clean_pointer()
excel_compiler.gen_graph()

This looses named ranges:
from koala.ExcelCompiler import ExcelCompiler
from koala.tokenizer import ExcelParser
excel_compiler = ExcelCompiler(file_name, ignore_sheets=ignore_sheets)
excel_compiler.clean_pointer()
parser = ExcelParser()
tokens = parser.parse(model.formula)
inputs = parser.getOperandRanges()
excel_compiler.gen_graph(inputs=["Temp_min", "Temp_max"], outputs=["GrowingDegreesDay"])

And so does this:
from koala.ExcelCompiler import ExcelCompiler
from koala.tokenizer import ExcelParser
from koala.Spreadsheet import Spreadsheet
excel_compiler = Spreadsheet.from_file_name(file_name, ignore_sheets=ignore_sheets)
excel_compiler.clean_pointer()
parser = ExcelParser()
tokens = parser.parse(model.formula)
inputs = parser.getOperandRanges()
excel_compiler.gen_graph(inputs=["Temp_min", "Temp_max"], outputs=["GrowingDegreesDay"])

I think it's to do with the call to read_named_ranges(). Moving the gen_graph method from ExcelCompiler to the Spreadsheet object has interrupted something or put it out of order.

**Comment by bradbase** [comment]
Have fixed it. Will issue a new PR.

**Pull request closed without merging**
