### PR TITLE
Tokenize newlines

### PR DESCRIPTION
**Pull request by Brad-eki**
added support for multi-line formulas

### CODE REVIEW

**Comment by vallettea** [comment]
Thanks for your work ! can one of you can update the version number in this PR so i can close it and push the last version to pipy ?

**Comment by brianmay** [comment]
Thanks for this pull request. I hope you don't mind, I cleaned it up a bit and made pull request #168.

**Comment by Brad-eki** [comment]
@brianmay no problem whatsoever

**Comment by vallettea** [comment]
just push the last version to pipy.
thanks for your contributions

**Pull request merged**
