### PR TITLE
Merge spreadsheet and excelcompiler class

### PR DESCRIPTION
**Pull request by danielsjf**
This to facilitate future enhancements as suggested in #64.

Warning, this pull in its current form will conflict with the other open pull request due to the same changes in the tox files. The test won't pass without these changes.

### CODE REVIEW

**Comment by brianmay** [comment]
As predicted, conflicts now need fixing in this and your other pull requests.

**Comment by brianmay** [comment]
I am somewhat unclear with this change. Currently we have from `README.md`:

```
c = ExcelCompiler("examples/basic.xlsx")
sp = c.gen_graph()
```

Where sp, I believe is a spreadsheet. How will this look after the change? Maybe `README.md` needs to be updated too? Would this do the same thing after this pull request?

```
sp = Spreadsheet("examples/basic.xlsx")
```

**Comment by danielsjf** [comment]
@brianmay indeed you are right. The way as currently described in the readme would still work, albeit with deprication warnings. The second line is indeed the recommended new approach. Since this will change a bit how the package works, I'm certainly open for discussions before this one is merged. The same for #189 and #191 that build upon this one.

**Comment by brianmay** [comment]
There are conflicts that need resolving.

I have no dramas with this change myself, it looks like it simplifies an aspect that was causing me a bit a confusion - but would be nice if we could get opinions from the wider koala community. Assuming there is a wider koala community :-).

To maintain semver versioning (major.minor.patch), the next release after this is incorporated would have to increment the minor version number. Then when we remove the deprecated code, we would need to increase the major version number.

**Comment by vallettea** [comment]
@danielsjf It's great you make so much contributions. Could you just fix these little conflicts so we can start merging your pull requests ?

**Comment by danielsjf** [comment]
@vallettea, this pull requests involves quite a bit of copying (nature of merging the two classes). I've recently made a few changes in some of the root functions in a few of my pulls. Therefore I want to thoroughly check this before resolving the conflicts.

I have a few more higher priority fixes before I will focus on this one. The other three as defined just now can be merged in the meantime.

**Comment by vallettea** [comment]
ok as you prefer

**Comment by danielsjf** [comment]
@brianmay, @vallettea, this one can be merged.

**Comment by vallettea** [comment]
looks good

**Pull request merged**
