### PR TITLE
Fix #N/A

### PR DESCRIPTION
**Pull request by altosz**
@vallettea 
**Fixed bug**: #N/A values in Excel are treated as 0 value.

**Given**:

- cell A1 in Excel has value '#N/A'
- cell B1 in Excel has formula '=A1*5'

In Excel B1 is evaluated to '#N/A'.
In koala B1 is evaluated to 0.

PS: I also fix some pep8 warning in files/lines that I touch.

### CODE REVIEW

**Comment by altosz** [comment]
@vallettea any comments? does the proposed solution fit the general flow?

**Comment by vallettea** [comment]
sorry for the late response, I'm on holidays. 
Thanks for this work. Can you just increment the version number in package.json so I can publish it on pypi

**Comment by altosz** [comment]
I have incremented version number in setup.py
https://github.com/anthill/koala/pull/136/files#diff-2eeaed663bd0d25b7e608891384b7298R10

Did not find any package.json.
@vallettea

**Comment by vallettea** [comment]
sorry about package.json (I did too much nodejs these days).
Perfect, pushing it now.

**Comment by altosz** [comment]
Thanks, @vallettea 
Have a nice vacation

**Pull request merged**
