### PR TITLE
Fix resolve range

### PR DESCRIPTION
**Pull request by danielsjf**
This pull request solves two types of issues:
* Where a range covers empty cells. Before they were dropped, which might cause issues with functions like MATCH().
* Where a range is row or column style (e.g. 1:1 or A:A).

Both issues are solved by adding the empty cells to the graph when they occur in a range. For row or column style ranges, only empty cells within the sheet dimension are added. For instance, if A5 is the lowest row and E1 is the furthest column, the sheet dimensions are E (5), 5. A range 3:3 would be evaluated as (A3, B3, C3, D3, E3).

The test won't pass until the other pull requests are merged.

### CODE REVIEW

**Comment by danielsjf** [comment]
#72 might be solved after this, but the issue lacks details on the exact problem.

**Comment by danielsjf** [comment]
Apparently the tests do not automatically rerun after another merge so a small edit should do the trick to rerun the tests.

**Comment by vallettea** [comment]
@danielsjf thanks for you work. Normally the tests should run after each commit.

**Comment by danielsjf** [comment]
@valletea, thanks. All five pull requests are ready to merge.

**Comment by brianmay** [comment]
Test failures need addressing...

**Comment by danielsjf** [comment]
Moving to #186 in favour of this one.

**Pull request closed without merging**
