### PR TITLE
Fix json dump/load

### PR DESCRIPTION
**Pull request by altosz**
@anthill, 
**Information about edges of a graph was not serialized to json.** 

The graph could not be serialized to json because data['links'] contained Cell objects. I had to save this information in order to restore it later.

Fixed:
1. `dump_json()`: save information about edges
2. `load_json()`: restore information about edges.
3. `Spreadsheet.load_json()` did not pass pointers argument to spreadsheet constructor - as a result the arguments of constructor were misplaced.

### CODE REVIEW

**Comment by vallettea** [comment]
thanks a lot !

**Comment by altosz** [comment]
@vallettea, what should be done to make this code available in an updated package (which I could install via pip)?

**Comment by vallettea** [comment]
I can do it but next time just update the version number in setup.py

Envoyé de mon iPhone

**Comment by vallettea** [comment]
just pushed the last version

**Pull request merged**
