### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by altosz**
Hi, @vallettea !

To improve performance I've made following changes:
1. remove print() statements during file parse. I suggest to use logging module further if debug output is required.
2. apply EAFP principle: replaced some if/else with try/catch when else branch is supposed to be rare. This principle has been applied to checks `if address not in self.cellmap`
3. replace some frequently accessed Cell properties with direct access to attributes (we do not loose time on function call). This has been applied when there is no @property.setter
4. evaluate string for Cell.address property only once and do not loose time on evaluating string on each property access
5. minor: remove unnecessary dict lookup (when we have already made the same lookup and know the result)
6. replace type() with isinstance()

These changes gave approx. 10% boost both for parsing excel file (due to no print statements) and for setting values + evaluating. I've tested on 1000 evaluation of 10 000 excel files.

PS: I've increased the version number too

Thanks and regards

### CODE REVIEW

**Comment by vallettea** [comment]
Thanks for your work. If more performance is needed cython makes a big difference from what I recall.

**Comment by altosz** [comment]
@vallettea, converting current koala code to cython would require plenty of time

**Comment by vallettea** [comment]
if you want to optimize each function, but without rewriting nothing, you can ask cython to create a c version and it already boosts the computation time

**Comment by altosz** [comment]
I've tried 
```
import pyximport
pyximport.install(pyimport=True)

from koala.ExcelCompiler import ExcelCompiler
```


as a quick solutions and got the following error:

````
Traceback (most recent call last):
  File "test_seq.py", line 10, in <module>
    from koala.ExcelCompiler import ExcelCompiler
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 419, in load_module
    return load_module(fullname, source_path, so_path=so_path, is_package=is_package)
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 233, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})
  File "/usr/local/lib/python2.7/site-packages/pyximport/pyximport.py", line 216, in load_module
    mod = imp.load_dynamic(name, so_path)
  File "__init__.py", line 3, in init koala.__init__
ImportError: Building module koala failed: ['ValueError: Attempted relative import in non-package\n']
````

Is there any other way to quickly create a c version of koala? (I'm not familiar with cpython)

**Comment by vallettea** [comment]
that the good way but you need to rename all imported files extensions in .pyx

**Comment by altosz** [comment]
I suppose that flag pyimports=True enforces compilation of .py sources also.

пт, 12 окт. 2018 г. в 17:48, Alexandre Vallette <notifications@github.com>:

**Pull request merged**
